version: "3.8"
services:
    # app:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     image: app
    #     container_name: app
    #     restart: unless-stopped
    #     tty: true
    #     environment:
    #         SERVICE_NAME: app
    #         SERVICE_TAGS: dev
    #     working_dir: /var/www
    #     volumes:
    #         - .:/var/www
    #         - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    #     networks:
    #         - app-network

    # webserver:
    #     image: nginx:alpine
    #     container_name: nginx-webserver
    #     restart: unless-stopped
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - .:/var/www
    #         - ./docker-compose/nginx:/etc/nginx/conf.d/
    #     networks:
    #         - app-network

    adminer:
        image: adminer:latest
        container_name: adminer
        ports:
            - 8080:8080
        networks:
            app-network:
        restart: unless-stopped

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=$DB_DATABASE
            - MYSQL_ROOT_PASSWOR=$DB_PASSWORD
            - MYSQL_PASSWORD=$DB_PASSWORD
            - MYSQL_USER=$DB_USERNAME
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
