version: "3"
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: stc_va
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: tathanh200320
            MYSQL_USER: stc_va
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql:
        driver: local
    redis:
        driver: local
